hydra:
  run:
    dir: .

data:
  batch_size: 16

model:
  _target_: exdark.models.exdarkdedicatedmodels.fasterrcnn.FasterRCNN
  optimizer:
    _target_: torch.optim.SGD
    _partial_: true
    momentum: 0.9
    weight_decay: 0.0005
  scheduler:
    _target_: torch.optim.lr_scheduler.MultiStepLR
    _partial_: true
    milestones: [15, 30]
    gamma: 0.1
  lr_head: 0.005
  lr_backbone: 0.0005

trainer:
  max_epochs: 150
